services:
  - type: web
    name: sys-dev-portf
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.19.0
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_CONTACT_EMAIL
        sync: false
      - key: NEXT_PUBLIC_RESUME_URL
        sync: false
